export const LOAD_INVENTORY_SUCCESS = "LOAD_INVENTORY_SUCCESS";
export const LOAD_GAME_CONSOLES_SUCCESS = "LOAD_GAME_CONSOLES_SUCCESS";
export const SAVE_GAME_SUCCESS = "SAVE_GAME_SUCCESS";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

